### ISSUE TITLE
ImUnsortedMap should refine return type of ImMap.assoc(Map.Entry)

### ISSUE THREAD

**Issue by pniederw** [GlenKPeterson/UncleJim#13] opened 2016-09-13 04:08 UTC
It does so for `assoc(K, V)`, but not for `assoc(Map.Entry<K, V>)`.

**Comment by GlenKPeterson** [comment] 2016-09-13 13:24
Fixed in 2.0.9.  I think the root cause of the issue was not doing 100% test coverage on the new code.  If I had, I would have written sub-classes as part of the test.  I have 100% coverage on every file I touched in this release.  I'll do that probably fix the coverage of the other interfaces this weekend unless you report more bugs.

## 2016-09-13 Release 2.0.9:
* Fixed return type of ImUnsortedMap and MutableUnsortedMap.assoc(Map.Entry)
* Made ImUnsortedSet use MutableUnsortedSet's implementation of union() instead of the other way around.
* Added tests.

**Closed** 2016-09-13 13:25 UTC
Labels: bug
